### ISSUE TITLE
will it work with php7.4 too?

### ISSUE THREAD

**Issue by fuco809** [Whissi/realpath_turbo#17]
a) why php does not integrate a solution for this in new releases?

b) will realpath_turbo works with php7.4 too?

**Comment by Whissi** [comment]
> b) will realpath_turbo works with php7.4 too?

It's working with PHP 7.4, see tests from https://travis-ci.org/github/Whissi/realpath_turbo


> a) why php does not integrate a solution for this in new releases?

Ask the PHP project. But keep in mind that this turbo has side effects on security and is therefore not supposed to run on mass hosting platforms for example.

**Comment by fuco809** [comment]
thanks for your work. also for php8.0 - but theres no test for this version on  https://travis-ci.org/github/Whissi/realpath_turbo
8.0 = master OK, u are right szepeviktor

**Comment by szepeviktor** [comment]
Isn't `PHP=master` PHP 8?
