### ISSUE TITLE
Cannot compile under php 7.0+

### ISSUE THREAD

**Issue by roman4e** [Whissi/realpath_turbo#2]
There are lots of errors while compiling for the PHP7.0

**Comment by Mikk3lRo** [comment]
Try the fork I made a couple of days ago, it works for me:
https://github.com/Mikk3lRo/realpath_turbo

**Comment by Whissi** [comment]
Landed in develop branch. Will be part of v2 release.

**Comment by rayward** [comment]
@Whissi is this ready for release?

**Comment by Whissi** [comment]
It is currently in beta phase. So anybody testing the develop branch is welcome.
I plan do add some basic test coverage later and do a real RC release before the final release...

Final v2 is expected not before November.

**Comment by rayward** [comment]
Thanks! We're in the process of upgrading our infrastructure to PHP 7, so we'll do some testing.

**Comment by Whissi** [comment]
I merged the changes into master and have released [v2.0.0 RC1](https://github.com/Whissi/realpath_turbo/releases/tag/v2.0.0rc1). Would be nice to get some feedback. Final release is scheduled for November.
