### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by szepeviktor** [Whissi/realpath_turbo#4]
Please implement some **very basic** tests in PHP.

**Comment by szepeviktor** [comment]
`make test` says:

> No tests were run.

**Comment by Whissi** [comment]
What do you want to test? This extension only hooks into PHP's startup method, disable `open_basedir` when set so that PHP itself doesn't disable realpath cache and after initialization it will re-set `open_basedir`.

I have no idea how we could test that in PHP's test suite...

**Comment by szepeviktor** [comment]
"OK" Tests

Execute some PHP code, e.g. read extenstion config with `ini_get()`

"Failure" Tests

Execute something outside open_basedir

**Comment by Whissi** [comment]
OK, I added some test. Did I mention that we are all green now (https://travis-ci.org/Whissi/realpath_turbo/builds/165604130)?

Closed via 99847d1edc0ab151582f13a278c6f6c1eb4848c0

**Comment by szepeviktor** [comment]
Thank you.
